### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mayorau3** [mayorau3/furima-29348#10]
+ Heroku上のフリマアプリのURL
https://furima-29348.herokuapp.com/

+ Basic認証
 ID : furimayo
 PASS : 222222

+ 出品者用のメールアドレスとパスワード
 MAIL : seller@gmail.com
 PASS : seller123

+ 購入者用のメールアドレスとパスワード
 MAIL : buyer@gmail.com
 PASS : buyer123

+ 購入用カード情報
 番号 : 4242424242424242
 期限 : 12月 / 28年
 セキュリティコード : 123

***

最終課題、基本実装が完了し、Heroku上にアップしましたので、
挙動確認宜しくお願いいたします。

**Comment by mo1015** [comment]
小池さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

※**補足**　商品購入後も、出品者が商品情報を編集できてしまいます。可能であれば購入済の商品情報は編集できないようにしましょう！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by mayorau3** [comment]
@mo1015 
レビューありがとうございました！
補足コメントもありがとうございます。
やってみます！
